services:
  app:
    image: docker.io/markojerkic/sprint-planing:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      APP_ENV: ${APP_ENV}
      PORT: ${PORT}
      BLUEPRINT_DB_URL: ${BLUEPRINT_DB_URL}
      SESSION_SECRET: ${SESSION_SECRET}
    volumes:
      - sqlite_bp:/app/data
volumes:
  sqlite_bp:
